In [1]:
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings(action='once')
import numpy as np
import data_functions as df
import text_functions as tf
import analitics_functions as af
import lda_functions as lf

from sklearn.decomposition import LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot as plt
%matplotlib inline

#задаем режим работы - FAST/NORMAL
mode='FAST'
isDebug=True

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py:369: DeprecationWarning: invalid escape sequence \[
  _match = re.compile("(datetime64|M8)\[(?P<unit>.+), (?P<tz>.+)\]")
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py:399: DeprecationWarning: invalid escape sequence \w
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\strings.py:677: DeprecationWarning: invalid escape sequence \d
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:2679: DeprecationWarning: invalid escape sequence \*
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py:1001: DeprecationWarning: invalid escape sequence \m
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py:1062: DeprecationWarning: invalid escape seque

In [2]:
#создаем/загружаем массивы данных
questionsAnswers, questionsOriginal, answersOriginal, questionsNormalized=df.load_data(mode)
dictionary=df.create_dictionary(questionsNormalized,10,3000, mode)

#делаем матрицу слов и документов и выводим разряженность
vectorizer = CountVectorizer(analyzer='word', vocabulary=dictionary)
dataVectorized = vectorizer.fit_transform(' '.join(t) for t in questionsNormalized[:])
matrixDoc2words=np.array(dataVectorized.todense())
if isDebug:
    af.check_sparsity(matrixDoc2words)
    
# грузим лучшую модель исходя их той, которая найдена по gridSearch c соседнем jupyterNoteBook
ldaModel, ldaOutput=lf.load_best_lda(calculatedModel='DUMP_bestLDAModel.pkl', calculatedModelOutput='DUMP_bestLDAModelOutput.pkl')

#получим вектор столбец с темой по каждому документу   
question2themesVector=np.argmax(ldaOutput,axis=1)

#показать все ключевые нормированые слова исходя из модели по темам
if isDebug:
    lf.show_most_freq_words_per_theme_via_lda(ldaModel, vectorizer.get_feature_names())

#показать названия кластеров,то есть
#уникальные леммы слов в темах модели и сопоставляем их с наиболее часто встречающиеся из всех ненормированных слов
mostFreqWordsPerThemes=lf.get_most_freq_words_per_theme(vectorizer.get_feature_names(), ldaModel, questionsOriginal)
lf.show_most_freq_words_per_theme(mostFreqWordsPerThemes)


loading data, please wait...
loading data DONE
<Загрузка из дампа>

Всего слов в словаре: 3307
Sparsicity (матрица разряженности нулей и неНулей):  0.3007117421210558 %

Загрузка модели...
Загрузка модели завершена!

Все ключевые нормированые слова в найденных темах:
Тема 0: ['срок' 'действ' 'заявлен' 'заявк' 'скольк' 'написа' 'ответ' 'недел'
 'прошл' 'времен' 'сайт' 'ждат' 'дебетов' 'дизайн' 'перевыпуск']
Тема 1: ['услуг' 'платеж' 'месяц' 'получа' 'отключ' 'возможн' 'мобильн' 'оформ'
 'книжк' 'клиент' 'зарплат' 'плат' 'работа' 'сбер' 'квартир']
Тема 2: ['сегодн' 'паспорт' 'заблокирова' 'поменя' 'баланс' 'снят' 'числ' 'пришл'
 'потеря' 'узна' 'готов' 'арест' 'итог' 'полож' 'оста']
Тема 3: ['работа' 'говор' 'обслуживан' 'звон' 'оператор' 'момент' 'ответ' 'позвон'
 'выдач' 'наход' 'моментум' 'сайт' 'клиент' 'прост' 'служб']
Тема 4: ['сотрудник' 'узна' 'работ' 'должн' 'указа' 'документ' 'обращен' 'договор'
 'привяза' 'хотел' 'писа' 'услов' 'ситуац' 'центр' 'город']
Тема 5: ['рубл' 'верну

In [3]:
# ВВЕДИТЕ ВОПРОС ТУТ (curQuestionRaw)
curQuestionRaw='по «пополняй» и ограничение на максимальную сумму вклада, которая равна первоначальному увеличенному в 10 на разницу между фактической и максимальной будут по ставке умноженной на 1/2. я открыла счет "пополняй " год назад в "онлайн". мой взнос равнялся 1000 руб., и каждый месяц я счёт на 1000 когда на 11000 руб., было предупреждение о максимального остатка на счёте. это как  что больше 10000 руб. (в данном случае) на счету нельзя я открыла счет на срок до 3 лет, с пролонгацией и пополнением счёта. быть, есть  нибудь другой вклад без на максимальный остаток вклада?'
#тестовые вопросы, которые использовались для отладки
#curQuestionRaw='по «пополняй» и ограничение на максимальную сумму вклада, которая равна первоначальному увеличенному в 10 на разницу между фактической и максимальной будут по ставке умноженной на 1/2. я открыла счет "пополняй " год назад в "онлайн". мой взнос равнялся 1000 руб., и каждый месяц я счёт на 1000 когда на 11000 руб., было предупреждение о максимального остатка на счёте. это как  что больше 10000 руб. (в данном случае) на счету нельзя я открыла счет на срок до 3 лет, с пролонгацией и пополнением счёта. быть, есть  нибудь другой вклад без на максимальный остаток вклада?'
#curQuestionRaw='я гражданин украины, хотел бы снять деньги на территории россии в сбербанке с долларовой карточки украинского банк. если это возможно, то какая будет комиссия? снять можно только в банкомате или в отделении сбербанка? в чем возможно снять в рублях или долларах?'
#curQuestionRaw='а если того номера к которой прикреплена карта нету. т.е. утеряна сим-корта, но номер помню.'
curQuestionNorm=[' '.join(tf.clean_text(curQuestionRaw))]
curQuestionVectorized = vectorizer.transform(curQuestionNorm)
curQuestionTopicNum=lf.get_num_topic(curQuestionVectorized, ldaModel)
curQuestionVectorized = vectorizer.transform(curQuestionNorm).toarray()[0]

C:\ProgramData\Anaconda3\lib\site-packages\nltk\corpus\reader\wordlist.py:28: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Users\\mike\\AppData\\Roaming\\nltk_data\\corpora\\stopwords\\russian'>
  return concat([self.open(f).read() for f in fileids])


sddsdds


In [4]:
#найти и показать 5 ближайших вопросов через темы модели
top5MinDist,top5MinDistIdx = lf.get_5_nearest_Q_and_A_via_lda_probs([i[curQuestionTopicNum] for i in ldaOutput], isDebug)

lf.calculate_summary_stats_for_method(curQuestionVectorized, matrixDoc2words[top5MinDistIdx])
print('\n' + '--==Ближайшие пять вопросов среди всех вопросов (через темы модели)==--')
lf.show_5_nearest_Q_A_prob(questionsOriginal, answersOriginal, top5MinDist, top5MinDistIdx, isDebug)

#найти 5 ближайших вопросов через косинус
top5MinDist,top5MinDistIdx = lf.get_5_nearest_Q_and_A_via_cos(curQuestionVectorized, matrixDoc2words, isDebug)

lf.calculate_summary_stats_for_method(curQuestionVectorized, matrixDoc2words[top5MinDistIdx])
print('\n' + '--==Ближайшие пять вопросов среди всех вопросов (через близость вектора слов)==--')
lf.show_5_nearest_Q_A_prob(questionsOriginal, answersOriginal, top5MinDist, top5MinDistIdx)

# по входному вектору найти через cos наиболее 5 близких вопросов + ответов + вероятность ВНУТРИ КЛАСТЕРА
#ближайший кластер curQuestionTopicNum
question2currentThemeIdx=np.where(question2themesVector==curQuestionTopicNum)
matrixDoc2wordsCurrentTheme=matrixDoc2words[question2currentThemeIdx]

top5MinDist,top5MinDistIdx = lf.get_5_nearest_Q_and_A_via_cos(curQuestionVectorized, matrixDoc2wordsCurrentTheme, isDebug)

lf.calculate_summary_stats_for_method(curQuestionVectorized, matrixDoc2wordsCurrentTheme[top5MinDistIdx])
print('\n' + '--==Ближайшие пять вопросов среди всех вопросов в этом кластере (через близость вектора слов)==--')
lf.show_5_nearest_Q_A_prob(questionsOriginal[question2currentThemeIdx], answersOriginal[question2currentThemeIdx],
                        top5MinDist, top5MinDistIdx, isDebug=isDebug)

[0.9499965679764094, 0.9460338859963738, 0.9389833974512926, 0.9249981748027674, 0.9249959144430323]
[   69    21   109 27118 18333]
Сводное значение, рассчитаное через cos=  0.50052

--==Ближайшие пять вопросов среди всех вопросов (через темы модели)==--
ВОПРОС: в г.омске положил на вклад "сохраняй"(на 1 месяц с последующей пролонгацией) деньги,могу ли снять деньги в москве, какова будет комиссия с этой суммы при отправке и получении денег в  филиале сбербанка? сколько времени потребутся для получения?
ОТВЕТ:   вы можете получить денежные средства по вкладу в любом отделении сбербанка, как с открытием счета, так и без открытия счета. возможен запрос, как всей суммы вклада, так и части вклада (если предусмотрено условиями вклада). при этом необходимо оформить заявление о переводе ф. №143, предоставить сберегательную книжку (в случае ее утраты к заявлению о переводе ф. №143 должно быть приложено заявление об утрате сберегательной книжки ф. №285) и паспорт. срок исполнения перевода 5 раб

C:\Users\mike\Anaconda2\ya_sam\lda_functions.py:138: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(u, v) / norm(u) / norm(v)  # cosine of the angle


[0.54997194 0.54997194 0.54433105 0.91233125 0.56853524]
[10933 36232 24082 30150  1641]
Сводное значение, рассчитаное через cos=  3.12514

--==Ближайшие пять вопросов среди всех вопросов (через близость вектора слов)==--
ВОПРОС: какой сейчас максимальный процент по вкладу?
ОТВЕТ:  максимальный размер процентной ставки установлен по вкладам «сохраняй» и «сохраняй онлайн». при их открытии на сумму от 700 000 рублей на срок от 6 месяцев до 1 года он составит 10,30% (10,52% при условии капитализации) и 11,25% (11,52%) соответственно. более подробная информация о вкладах и установленных по ним процентным ставкам в зависимости от суммы и срока размещена на сайте по ссылке http://www.sberbank.ru/tatarstan/ru/person/contributions/deposits/.
ВЕРОЯТНОСТЬ: 0.5499719409228704

ВОПРОС: , я открыл вклад пополняй онлайн на сумму 14000 рублей. до какой суммы я могу пополнить этот вклад и каков процент начисления будет если я превышу максимальную сумму?
ОТВЕТ:  если сумма вклада превысит сумму, на кот